### ISSUE TITLE
breaks webpack: 'return' outside of function

### ISSUE THREAD

**Issue by zaggino** [airbnb/js-shims#12]
This package depends on "promise.allsettled": "^1.0.0",

works when forced to `1.0.1`, but when resolved to `1.0.2` breaks webpack builds with:

```
Creating an optimized production build...
Failed to compile.

./node_modules/is-map/index.js
SyntaxError: /usr/app/node_modules/is-map/index.js: 'return' outside of function (12:1)

  10 | \t\treturn false;
  11 | \t};
> 12 | \treturn;
     | \t^
  13 | }
  14 | 
  15 | var $mapHas = $Map ? Map.prototype.has : null;
```

**Comment by lencioni** [comment]
This seems to be a problem with the promise.allsettled package. It looks like you already opened an issue over there: https://github.com/es-shims/Promise.allSettled/issues/7

cc @ljharb

**Comment by ljharb** [comment]
Top level return has always been valid in node modules; this seems to be a problem with a webpack configuration.

**Comment by ljharb** [comment]
v2.0.1 of both is-map and is-set have been released.
