### ISSUE TITLE
iOS 9.3, Mobile Safari 9.0 function.prototype.name errors

### ISSUE THREAD

**Issue by richardvenneman** [airbnb/js-shims#6]
Hi,

Thanks for this library. Most of the environments I tested seem to get shimmed correctly, however trackjs was still reporting Script Errors. After some debugging it appears that Mobile Safari on iOS 9.3 stops parsing with "Attempting to change configurable attribute of unconfigurable property".

![screen shot 2017-07-20 at 22 44 48](https://user-images.githubusercontent.com/75705/28438340-1b8448aa-6d9e-11e7-9b4a-e15b7fb8c77e.png)
![screen shot 2017-07-20 at 22 54 52](https://user-images.githubusercontent.com/75705/28438479-7c198d88-6d9e-11e7-864c-ac07ed0106bb.png)

I'm not really sure if I should actually file an issue at the function.prototype.name repo, but I was hoping someone here might know how to proceed from here. Any help is appreciated!

airbnb-js-shims: "^1.2.0"

**Comment by ljharb** [comment]
Thanks - that repo is probably a better place to file it, but we can leave this open in the meantime to track it.

When you do, would you mind providing the output of `function foo() {}.name === 'foo'`? Also, are you mangling function names when you minify? If so, that will definitely break it.

**Comment by ljharb** [comment]
I added a fix that works even when function names are mangled.

Hopefully that solves the problem; it'll be released soon.

**Comment by richardvenneman** [comment]
Great stuff, thanks @ljharb! I can confirm that your fix works in production.

**Comment by ljharb** [comment]
Thanks for the report :-)

I ended up building https://www.npmjs.com/package/uglify-register so that I could write a regression test for this, so that was fun!
